packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: true
  bufferutil: set this to true or false
  utf-8-validate: set this to true or false
  bigint-buffer: set this to true or false
